name: xtime-dev
channels:
  - conda-forge
dependencies:
  - cftime
  - codecov
  - dask
  - pip
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-sugar
  - pytest-xdist
  - scipy
  - sparse
  - xarray
