name: xtime-dev
channels:
  - conda-forge
dependencies:
  - cftime
  - codecov
  - dask
  - pip
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-sugar
  - pytest-xdist
  - scipy
  - xarray
  - pip:
      - git+https://github.com/pydata/xarray.git
      - git+https://github.com/Unidata/cftime.git
